### ISSUE TITLE
result table cant be created

### ISSUE THREAD

**Issue by reza2521ff** [krausest/js-framework-benchmark#1128]
ERROR in C:\Users\Reza\Desktop\Mono 1\js-framework-benchmark\webdriver-ts-results\src\reducer.ts
[tsl] ERROR in C:\Users\Reza\Desktop\Mono 1\js-framework-benchmark\webdriver-ts-results\src\reducer.ts(24,125)
      TS2339: Property 'issues' does not exist on type '{ name: string; dir: string; keyed: boolean; }'.
Child HtmlWebpackCompiler:

**Comment by krausest** [comment]
Just a wild guess, since I checked that a clean version builds fine on windows and you provided little information what fails.

Can you please take a look at webdriver-ts-results\src\results.ts in VSCode? I'd guess that there's a line that might stem from a old directory or so that contains no or an invalid package.json which causes a wrong entry here. 

If that's not the case, please provide more information what npm command you're running.

**Comment by reza2521ff** [comment]
Hi Stefan,
Thanks for replying !
I did all the steps according to your instructions on github but on step
2.5 ( building the table ) when I write command npm run results I ran to an
error which indicates the "issues" property does not exist.
I checked webdriver-ts-results\src\results.ts in VSCode and in the
frameworks array at the end there is no issues property. I am going to
attach the pic from results.ts so that you look it over.
Thank you!

**Comment by krausest** [comment]
Can you please attach a ZIP of webdriver-ts-results/src?

**Comment by reza2521ff** [comment]
Sure, here it is.

**Comment by krausest** [comment]
I'm afraid I don't see the attachment.

**Comment by reza2521ff** [comment]
[src.zip](https://github.com/krausest/js-framework-benchmark/files/9873303/src.zip)

**Comment by reza2521ff** [comment]
Sorry would you clarify what the problem was?

**Comment by krausest** [comment]
Can you please update and try if that fixes your issue? It seems that it compiles only when a framework with an issue is included. This is usually for vanillajs the case. I tweaked the code a bit, it should compile now.

**Comment by reza2521ff** [comment]
okay thank you!
