### ISSUE TITLE
Testing Result in Firefox

### ISSUE THREAD

**Issue by Ethkuil** [krausest/js-framework-benchmark#1185]
I can only see testing result in Chrome in [the website](https://krausest.github.io/js-framework-benchmark/). Will testing result in Firefox be added?

I'm curious about this mainly because it seems that Firefox supports wasm better.

It has been mentioned in issue #243 but have not been discussed in depth.

**Comment by krausest** [comment]
I think Firefox lacks a possibility to export performance traces in a way like chrome. Maybe I‘ll publish some results based on pure client side measurement in june or so…

**Comment by benmccann** [comment]
I expect that Firefox would give drastically different results. The top performers in the Chrome benchmark use `cloneNode` which is 2x slower on Firefox than `createElement` in a micro-benchmark I put together.

It might be interesting to run the benchmarks in Chrome, Firefox, and Safari and then combine their results perhaps in a weighted average based on market share.

**Comment by leeoniya** [comment]
> The top performers in the Chrome benchmark use `cloneNode` which is 2x slower on Firefox than `createElement` in a micro-benchmark I put together.

@benmccann can you post your micro-benchmark?

`cloneNode` may be slower when creating individual elements vs `createElement`, but that's not where its usefulness is. where cloneNode should outperform by a large margin is when replicating full structures (like `<Row>`) via a single cloneNode call, rather than re-creating this struct in a loop via 10x createElement/textContent/setAttribute/appendChild calls.

https://github.com/krausest/js-framework-benchmark/blob/5d756ad2946679b62b229d8779bdbf6ff988624f/frameworks/keyed/inferno/src/controller.jsx#L4-L19

**Comment by krausest** [comment]
We'll track this in #1383.
