### ISSUE TITLE
non-keyed description is not true for Binding.scala

### ISSUE THREAD

**Issue by Atry** [krausest/js-framework-benchmark#123]
In the section Non keyed results on page http://www.stefankrause.net/js-frameworks-benchmark5/webdriver-ts/table.html:
> In consequence inserting or deleting an element in the data array might append after or delete the last table row and update the contents of all elements after the inserting or deletion index.

It's not true for Binding.scala. Thanks to its [precise data binding](https://github.com/ThoughtWorksInc/Binding.scala#precise-data-binding) mechanism, the DOM managed by Binding.scala always precisely follows the same changes on upstream data.

**Comment by leeoniya** [comment]
in the "replace all rows" benchmark, the entire dataset is destroyed and replaced with new data. this means that the entire DOM must also be destroyed and recreated. the fastest this can be done is ~141ms (vanillajs and kivi). non-keyed implementations reuse the dom fro the new data because they do not, by definition, precisely bind the data to the dom. the fastest that this can be done is about ~54ms (vanillajs). if what you say is correct, then Binding.scala somehow outperforms vanillajs by 43.5%, which seems very highly improbable.

**Comment by Atry** [comment]
Because the current implementation explicitly reuse existing **view model**. See https://github.com/krausest/js-framework-benchmark/commit/0ec9ece496d6e7db98e1ee1a6eaec2ec2dd57a83#diff-48acb9e7c042c5a00bc2400c13805429R96

**Comment by leeoniya** [comment]
i'm not sure the details of how it works internally matter at all.

if deletion of data does not result in the deletion of the dom, then the two are not strictly bound. if the dom is reused then it is non-keyed - that is exactly the distinction the two tables are designed to make.

**Comment by Atry** [comment]
In Binding.scala, deletion of data causes immediate deletion of the DOM. However, in the current implementation of benchmark, when the user click `Create 1,000 rows` button, it does not remove data and recreate data if there are same number of existing data.

**Comment by leeoniya** [comment]
i understand. your store implementation does something different than all other store implementations in the keyed table. this difference causes it to behave as if it were non-keyed with respect to dom operations. in my opinion it is being classified properly with respect to how it ends up behaving. to put it another way, this implementation is incorrect for the keyed table. the goal of this split benchmark is to compare similar impls to avoid the situation that existed when the impls were in a single table and could not be fairly compared.

**Comment by Atry** [comment]
As I mentioned in https://github.com/krausest/js-framework-benchmark/issues/89#issuecomment-265178871

Keyed and non-keyed are not proper terms to describe behaviors. I hope we could use other terms, e.g. replacing row vs. replacing content.

**Comment by leeoniya** [comment]
i think keyed vs non-keyed is an accurate description of the dom to data binding behavior.

the issue is with ambiguity of how the store must behave for each method. however, all keyed implementations have identical bahavior for data mutation for the methods. Bindimg.scala chooses to do something else. i agree that the naming of the buttons and what they do in each case is not ideal, but it *is* uniform in all implementations except yours. why not just change your store to do what all other stores do? this whole discussion seems rather pointless, no?

**Comment by krausest** [comment]
@Atry 
My classification program webdriver-ts/src/nonKeyed.ts reports:
```binding.scala-v10.0.1 is non-keyed for 'run benchmark' and keyed for 'remove row benchmark'. It'll appear as non-keyed in the results```
I'd say this is correct since if you set the background-color of a row from outside the framework it'll stay when clicking "create 1,000 rows".
I also suggest you modify your implementation to be fully keyed which means to create fresh table rows. If you want we can have both a non-keyed and keyed version for binding.scala.

**Comment by Atry** [comment]
How about swap rows? Does it mean swapping content in two rows or swapping two rows?

**Comment by krausest** [comment]
The rows must be changed in the DOM. But in contrast to the other benchmarks the performance difference is negligible.

**Comment by leeoniya** [comment]
@krausest care to update the rendered table?

**Comment by krausest** [comment]
@leeoniya table is now updated (but please keep in mind that chrome was updated to version 56 and most results were measured on chrome 55)

**Comment by leeoniya** [comment]
interesting, i've actually been noticing a progressive downward perf trend in Chrome since v55. my 0% dbmonster overhead went from 1.17ms -> 1.31ms from 54->56.

**Comment by krausest** [comment]
@leeoniya I added temporarily a vanillajs...-56 version in the results table that was measured on chrome 56. Seems like performance didn't change on my MacBook from 55 to 56 (can't speak about 54).

**Comment by leeoniya** [comment]
@krausest you may not see a change in vanilla since it does a lot less than fuller libs. kivi seems relatively unaffected also. but something that domvm is doing is now running slower than before - it went from 1.10 & 1.09 -> 1.13 & 1.12 in recent updates without any impl or lib changes.
