### ISSUE TITLE
Why isn't jQuery in this Benchmark?

### ISSUE THREAD

**Issue by paranoid-android** [krausest/js-framework-benchmark#126]
This benchmark tool is great! I want you to know you've done some great work and I don't want the issue I'm reporting to detract from what's been done.

Still, I'm surprised jQuery hasn't been included in these benchmarks. I can see an argument being made that it's a not a framework like the others that are benchmarked. However, jQuery can create / read / update rows. For that reason, I'm a bit surprised it's not included. I personally think the addition of jQuery 3.1.1 (`https://code.jquery.com/jquery-3.1.1.min.js`) would be a great addition to this benchmark.

**Comment by leeoniya** [comment]
> I personally think the addition of jQuery 3.1.1 would be a great addition to this benchmark.

Most implementations are submitted as PRs by various authors. You are welcome to submit a jQuery version for inclusion.

**Comment by trotyl** [comment]
> I can see an argument being made that it's a not a framework like the others that are benchmarked.

The problem here is not about whether something is a framework, but whether something is data-driven.

What actually being tested is **how good a library/framework finding out what actual DOM manipulation is by data**, jQuery is not data-driven, so you do can test what's the slowdown of jQuery compare to the VanillaJS, but it does not make much sense to compare jQuery with other data-driven framework.

Besides, in most data-driven frameworks, it's still available for direct DOM manipulation, but that's not what being covered for this benchmark.

**Comment by krausest** [comment]
I must say I'm not particularly interested in adding jQuery. The purpose of this benchmark is to measure the cost of a framework over vanillaJs. And there are many good reasons why one would not use vanillaJs for a real world app. JQuery should be close to vanillaJs and if it's not close, zepto or some low level dom operation mixed with jQuery will be. The existence of vanillaJs should not be interpreted as a recommendation to use it for your next project but just to serve as a baseline (and in some cases it's already behind ;-)

**Comment by aminya** [comment]
Can we open this again? It is not about "the personal interest or preference", it is about having a reference for comparing the JavaScript DOM libraries. I see everywhere people bash jQuery and say that its performance is a bottleneck. 

If this benchmark framework wants to be a reference, it should definitely include jQuery.
