### ISSUE TITLE
How to add Test / Benchmark operations

### ISSUE THREAD

**Issue by Facronactz** [krausest/js-framework-benchmark#1268]
I have attempted to incorporate a new operation into the benchmark test, but my efforts have been unsuccessful thus far. The objective I am pursuing is relatively straightforward. Instead of solely adding 1,000 rows, I aim to include 1,000, 5,000, and 10,000 rows.

I would greatly appreciate a concise tutorial outlining the process, beginning with generating a description of the operation and concluding with the addition of a new row in the result table.

Thank you kindly.

**Comment by krausest** [comment]
Adding a test operation is actually pretty challenging, especially since you'd have to change all implementations.
The following steps should work:
1. Make sure you can trigger your operation with a click, e.g. by adding a button in the html to trigger creating 5,000 rows. I'd do this in one implementation only
2. Add a benchmark in the test driver for all test driver implementations (benchmarkCommons + benchmarkPuppeteer.ts etc.). Make sure you can run the test for that implementation. Maybe it would be easier to start with changing one benchmark to perform that new operation (e.g. modify benchRun in benchmarksPuppeteer.ts and try to invoke the operation. If that works, you can add a new benchmark and restore benchRun). 
4. Implement the operation for all implementations.

The code currently isn't optimized for adding operations. Having five test runners doesn't make it easier, so I'd also expect it to be quite hard work. Feel free to ask if you have specific questions! 

P.S: I'm not sure whether I'd merge a PR with a new operation. It would probably depend on the question whether the operation revealed something new and how complete the implementations were updated (I couldn't do it for all of them...).

**Comment by Facronactz** [comment]
Thank you for your response
> 1. Make sure you can trigger your operation with a click, e.g. by adding a button in the html to trigger creating 5,000 rows. I'd do this in one implementation only

Alternatively, may I inquire if it would be acceptable to bypass this requirement and instead simulate multiple clicks on the existing button? For instance, clicking the "Create 1,000 rows" button five times consecutively.

> 2. Add a benchmark in the test driver for all test driver implementations (benchmarkCommons + benchmarkPuppeteer.ts etc.). Make sure you can run the test for that implementation. Maybe it would be easier to start with changing one benchmark to perform that new operation (e.g. modify benchRun in benchmarksPuppeteer.ts and try to invoke the operation. If that works, you can add a new benchmark and restore benchRun).

It appears that there are three CPU benchmark runners available: Playwright, Puppeteer, and WebDriver. Could you please clarify whether the benchmark employs all three runners simultaneously or only one at a time? Additionally, I noticed a configuration in the common.ts file at line 80, featuring a variable named "BENCHMARK_RUNNER." Does this variable determine the runner that the benchmark uses?

**Comment by Facronactz** [comment]
Ok, now I get it. Instead of adding a new operation, I have opted to modify the existing operation and run the benchmark every time i do it, which seems to be a simpler and effective approach. 
I appreciate your assistance throughout this process. Thank you.
