### ISSUE TITLE
Please add Riot.js

### ISSUE THREAD

**Issue by niutech** [krausest/js-framework-benchmark#13]
http://riotjs.com

**Comment by krausest** [comment]
It's committed. 
Can you help with the code? Here are the issues I'm facing:
- The button id must not be named "update". But I need that name for the selenium webdriver. I'm currently adding the button on mount
- For the console logging I'd like to receive a callback after modifying the dom. The updated callback is currently executed twice.
- Performance is below expectation (currently one of the slowest). Can you judge if I'm doing something wrong?

**Comment by niutech** [comment]
What is is the error with `id="update"`? Can't you just give the button `id="my_update"` and on mount: `document.getElementById('my_update').id = 'update';`?

Since each tag is an [observable](http://riotjs.com/api/observable/), can't you just write: `this.one('updated', function () {...});` or use `MutationObserver` instead?

As for performance, Riot tags should not be compiled in-browser by `script type="riot/tag"`, but they should be [pre-compiled](http://riotjs.com/guide/compiler/#pre-compilation) using `riot` command.

**Comment by krausest** [comment]
Preliminary results are [here](https://cdn.rawgit.com/krausest/js-framework-benchmark/f7e3f9336c8b20bea2f2073f8814dee7022bd3bf/webdriver-java/table_update.html).
Must be doing something wrong or riot is indeed slow.

**Comment by avimar** [comment]
I don't understand the whole framework, but some ideas:

1) https://github.com/krausest/js-framework-benchmark/blob/master/riot-v2.5.0/row.tag:
You don't need to specify `select` and `remove` for each child tag.. especially if you KNOW you're going to make a ton of rows. Just put it in the parent and do `parent.select` and access the `event.item.id`, I see you already have the function.
1b) Why is your row tag full of "opts"? Yes: `<tr riot-tag="row" each={this.opts.data} data={this} no-reorder/>` -- you have no need for `data={this}` -- you've already passed in the data with the `each`... I think.  Then instead of `{ opts.data.id }` you just call `{id}`

2) Riot-next/v3.0 removed automatic child-inheritance, which should remove some of the load of new objects. but you'll need more `this.update()`'s, as that is getting removed as a default.

Maybe I can get some time to try that myself... is it simple to see if my change sped things up, or do I need to run a whole suite?

**Comment by avimar** [comment]
p.s. I see you pre-compiled it -- cool. I don't think that affects run time, only startup time.

**Comment by avimar** [comment]
Nope, I made all those updates I mentioned -- the code is cleaner, but it didn't seem to make any difference in timing.

Let's try updating to the next riot..

**Comment by avimar** [comment]
BTW when you need `npm install -g http-server` for it to run.
Also, the css is in the main root, so that doesn't work when you try to run a single framework because it's in the root of that framework.

**Comment by avimar** [comment]
Uhm updating to riot@next (riot@3.0.0-alpha.5) I don't get anything when I try to click the buttons nor errors. Ideas?

**Comment by krausest** [comment]
Thanks for your work.
I use to run http-server from the parent directory. You can then change into each directory and run the webpack build with npm run build-{dev|prod}.
I'm reopening the issue to watch the progress.

**Comment by GianlucaGuarini** [comment]
I would be nice to inform us before publishing invalid bench. I will see whether I could take a bit of time for a pull request
