### ISSUE TITLE
Feature: startup-time

### ISSUE THREAD

**Issue by martinoppitz** [krausest/js-framework-benchmark#137]
I think the startup-time is a important measure.

For example: vuejs need the component definition before rendering the app initial. I think that increase the start-up time by number of different components.

In big project you have a lot of components. That is very important.

**Comment by leeoniya** [comment]
this was literally just added.

see the second-to-last row: https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts/table.html

**Comment by martinoppitz** [comment]
Ouch.

Okay. Then we need more components. I freeze vue.js with more then 1.000 components.

**Comment by leeoniya** [comment]
i guess it depends on what your goal is. there are some frameworks where components add 0-overhead and you could literally have every node be a component. there are other frameworks where components carry some-to-a-lot of overhead due to state retention, etc.

i think that it makes sense to bench the fastest impl given the framework architecture and the task at hand. if a component is slower and not required to get the job done, then why write a slow impl? is it to demonstrate what beginner users should expect if they wrote a naive implementation in the most straightforward (or idiomatic) way possible? in that case, we can strip all event delegation, etc from each impl, also?

my $0.02

**Comment by krausest** [comment]
So I'm closing this issue.
