### ISSUE TITLE
🐛 benchmark 04_select1k failed: difference between mousedown and click is unusually long

### ISSUE THREAD

**Issue by MattParkerDev** [krausest/js-framework-benchmark#1460]
I am getting an error running a single benchmark (tried with vanilla js and blazor-wasm):

```
==== Results of PlausibilityCheck:
================================
The following benchmarks failed:
================================
Executing frameworks/keyed/blazor-wasm/bundeled-dist/wwwroot/ and benchmark 04_select1k failed: difference between mousedown and click is unusually long
Executing frameworks/keyed/blazor-wasm/bundeled-dist/wwwroot/ and benchmark 09_clear1k_x8 failed: difference between mousedown and click is unusually long
run was not completely sucessful Benchmarking failed with errors
```

**Comment by krausest** [comment]
Oh, that was me... I added a check yesterday due to #1442.
The duration I chose was long enough to prevent such an error on my macbook, but as it seems it was too low.
I commented out throwing the error. You could try to update, recompile via `npm run compile` in webdriver-ts and run again.
It would be nice if you could report here the maximum value for the "difference between mousedown and click is unusually long" message in the log file.

**Comment by Niedzwiedzw** [comment]
@krausest  couldn't you just start counting from `mousedown`? that would be most fair

**Comment by krausest** [comment]
We could measure from mousedown (but wouldn't be mouseup then be a better choice?)
But there's a random(?) delay for some frameworks like in this case:
![Screenshot 2023-11-04 at 11 09 34 AM](https://github.com/krausest/js-framework-benchmark/assets/3374055/4d725958-b0c7-48f2-be6e-13df561eba1f)
There's a delay of more than 3 msecs between mousedown and click. I don't know where this comes from.
I think it wouldn't help us getting better results if we added this delay. Nevertheless it should be considered cheating if someone put his logic in a mousedown handler.
