### ISSUE TITLE
90 percentile calculation make comparisons across browser versions impossible.

### ISSUE THREAD

**Issue by birkskyum** [krausest/js-framework-benchmark#1473]
It's hard to compare perf across chrome versions if the 90 percentile mean that the reference changes. 

Similar to how local testing with just a few frameworks also is affected, because there isn't a way to calibrate without the entire table.

It's probably best to make the scoring of a frameworks independent of it's competitors, and only depend on a reference like vanilla-1.

An example of how the new calculation cause confusion: https://www.youtube.com/live/yLjqh6dKdBc?feature=shared&t=14040

**Comment by leeoniya** [comment]
i think there's a long-standing goal of ensuring vanillajs is 1.00 across the board. imo a static basline is probably unlikely until that's closer to reality.

**Comment by krausest** [comment]
Hmm. Maybe I should have put a large disclaimer on the new results...

Actually I don't plan to adjust the weights with each browser version. I plan to do so only when they change significantly.
But comparison across browser versions can be dangerous since the benchmark drivers changes from time to time (as in chrome 118 when we measured to the commit event and changed the slow down factors).

The new calculation has two advantages:
* It reduces the influence of the two noisy benchmarks
* It allows less crazy, lower slow down factors.

**Comment by birkskyum** [comment]
That are good points. Sounds like a great idea with some overall disclaimers about what can, and more importantly can't, be readily compared in this benchmark. I i.e. wasn't aware that cross-browser comparisons generally were dangerous until now.
