### ISSUE TITLE
Wow, ladies and gentlemens! It turns out that the benchmark is crap, it doesn’t show speeds in real applications (this is wrong!) :-/

### ISSUE THREAD

**Issue by antonmak1** [krausest/js-framework-benchmark#1760]
Wow, it turns out everything we do is crap. Look - https://x.com/dan_abramov2/status/1796156983575232942. It turns out that this is just a simple joke, and how people interpret the benchmark "it's embracing". Like, it doesn't show anything in real life. Holy sh^t, I'm so shocked. They promote their sh^tty VDOM and then say that it's not the VDOM that's slow, but just the repository that's bad.

**Comment by antonmak1** [comment]
@syduki This is not a task in the usual sense, I'm just offended that the benchmark, thanks to which 100% modern frameworks began to work faster, because here people tested different approaches in different versions of chrome, just to speed up the result a little, like "everything is overestimated", like it's just a table with 3 components, etc.

**Comment by antonmak1** [comment]
@syduki Okay, whatever you say.

**Comment by leeoniya** [comment]
the twitter post is stupid; in applications with thousands of components, the framework overhead is _more_, not _less_.

**Comment by antonmak1** [comment]
@leeoniya I don't know, you'd have to ask @gaearon about this. He wrote the post on Twitter. React has long been one of the slowest in terms of speed, and rewriting code on such a scale to something else is simply a colossal amount of work, and perhaps even impossible. I don't know how things are scaled there or not, but there is just an obvious fact of the code, without any tricky terms. Load the code with even a million components, it will still be through for, cloneNode, textContent and similar things. And, the algorithm is there under the hood on VDOM and everything depends on it. And it is slow there. I just don't know why, maybe they programmed according to DRY, KISS and similar principles, that they didn't do it as faster, but as more maintainable - I don't really know. I remember this topic was already discussed in the programming community, that all these principles are only about the convenience of working in large companies and maintainability, rather than about speed. This is where you can come up with all sorts of nonsense about overhead and so on.

**Comment by leeoniya** [comment]
i'll just say that in poorly written applications, the bottleneck is usually not the framework, but in well written applications it definitely can be.

an easy example to see is scrolling around in virtualized grids/tables. `react-data-grid` is one of the fastest grid components for React, and the main cost after rendering/layout is in fact the framework/vdom.

https://adazzle.github.io/react-data-grid/#/MillionCells

![image](https://github.com/user-attachments/assets/4f0685e3-4a18-4c76-8238-6fe90b9d66ba)

**Comment by antonmak1** [comment]
What difference does it make to the code whether it is for(..;i<10;..) or for (...;i<100000000;...)

**Comment by antonmak1** [comment]
@leeoniya Or, what I guess here, we can ask @trueadm about React. He worked on it, he can tell you for sure.

**Comment by leeoniya** [comment]
i have not seen much evidence that _distinct_ components is something that makes a material difference. it all comes down to the vdom size that has to be re-generated and diffed for each re-render. if your vdom/dom is small and your rerenders are infrequent, then you can ignore the framework overhead. but if you are scrolling or mousemove and your vdom is large, then suddenly it makes a big difference and then your chose of framework will set the baseline for how much optimization is really possible. by the time you hit these not-so-edgecases, you cannot swap out the framework.

it is clear that React focuses on DX (and maybe interop with React Native) rather than pure DOM performance. calling this benchmark an embarrassment is no less of an embarrassment than making a blanket statement that "React is so fast you rarely need to worry about it".

it's hard to have these nuanced conversations over twitter or with a general webdev/react-conf audience that simply appeals to authority.

**Comment by fabiospampinato** [comment]
> i'll just say that in poorly written applications, the bottleneck is usually not the framework, but in well written applications it definitely can be

I think that's kinda the deep takeaway here. 

From the point of view of the React team what could they do to make Facebook faster? They just can't manually rewrite all the code for that, it would take too much time. They could give the users more power, perhaps by being able to more directly control updates by using signals or whatever, but usually while things like that increase the ceiling of performance they also lower the floor for it, that may easily cause Facebook to be slower if people wrote bad code. So what they seem to want to do instead is to raise the floor of performance so that worst case scenario stuff is less bad, but that happens to lower the ceiling for it too.

If you think about concurrent mode I think that fits this view perfectly, nobody else seems to want to implement it, I can't think of a scenario where I'd want to use it rather than fixing the root problem(s) in the app's code, but it does help sorta fight against bad user code. Also the way React works leads to less than ideal performance, but the code is potentially easier to statically analyze compared to something based on signals, if you could just fix the code you'd probably want to use signals, if you can't fix the code then you'd rather want it to be statically analyzable so that eventually you could throw a compiler at it.

The scenario where bad user code can be fixed is just not the one where they operate under.

(just my 2 cents, I have no insider knowledge on this stuff)

**Comment by antonmak1** [comment]
@fabiospampinato I don't know what to do. I just [tweeted](https://x.com/antonmak11) to everyone I could, who could influence react in any way. Billions of people use this library every day, and they are using the old approach in 2024, IT'S ALMOST 2025!!!!!!!!!!!

**Comment by antonmak1** [comment]
@fabiospampinato The former React maintainer writes nonsense about tests and other things, how can you do anything at all?

**Comment by fabiospampinato** [comment]
@antonmak1 Changing people's minds is borderline impossible, just pick or make whatever makes you happy I guess 🤷‍♂️ Not everyone is optimizing for the same goals.

Also it is true that this benchmark can easily be misinterpreted and that it doesn't tell the whole story. I think it's a good benchmark for what it is, fwiw.

**Comment by antonmak1** [comment]
@josephsavona @poteto @sebmarkbage @gsathya @acdlite @sophiebits @zpao @timneutkens @leerob You can speed up react by removing VDOM rendering or by using a better method? Why have there been better algorithms and code for years that show how incredibly easy it is to speed up a site, but billions of people still find it takes so long to load sites? Why is the speed so slow? How is it possible that the most popular website building tool in the world is so slow? Why should people laugh at it as something monolithic and unwieldy? Is it so hard to apply algorithms like Longest increasing subsequence and speed up a key implementation? There are tons of examples, how many in one test? Why should we be so arrogant about all this?

**Comment by antonmak1** [comment]
Even if it's a lot of work, what, there aren't a hundred people in the world who could speed up modern frameworks so well? Is that some kind of nonsense in your opinion?

**Comment by antonmak1** [comment]
@fabiospampinato Yeah, what's the problem with the goals? What, there's no goal to speed up the module so that billions of people load sites faster? This is just regular javascript code, is it so hard to do?

**Comment by antonmak1** [comment]
@fabiospampinato I don't want to change anyone's opinion. There are just dry facts. There is perfect code in fact, which works super fast. People can use it and that's it. Reach maximum capabilities, just a bunch of frameworks in this test write the same code differently. What could be here, what opinion? This is stupid mathematics, not someone's opinion.

**Comment by antonmak1** [comment]
@trueadm Maybe you can do something using old connections? You know that there is a perfectly fast code, unlike @gaearon, you literally work on it every day. Why is it so hard to change react to make it faster? So that people don't just laugh at the speed and big companies don't reject it because of slow speed?

**Comment by antonmak1** [comment]
I don't know, even if you write to Mark, it's so stupid!

**Comment by antonmak1** [comment]
So obvious! But, just a monolith, what can I say.

**Comment by antonmak1** [comment]
Okay, in fact, a benchmark is just a mathematical problem that has long been solved, but people just make variants of the solution in code. I don't know, in general I think there is no point in imposing something on someone, there are just actual speed indicators and code. This benchmark set the standard algorithm, and how people implement it is up to them. The standard will not go anywhere, because it is the base.
