### ISSUE TITLE
Updating keyed/react-tracked failed

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#1797]
As in #1789 I'm updating all implementations. Implementations that failed to update are moved in to the broken-frameworks folder.
Here's what I'm trying to update:
```
 react-tracked          1.7.11  →   2.0.1
 terser-webpack-plugin  5.3.10  →  5.3.11
 ```
The build fails with the following runtime error:
```
main.js:2 Uncaught TypeError: (0 , r.memo) is not a function
    at main.js:2:187896
    at main.js:2:189981
```
@dai-shi Can you take a look at this?

**Comment by dai-shi** [comment]
Hi, thanks for taking care of it.

Just taking a quick look: Since v2, react-tracked dropped custom `memo` as now it's compatible with React.memo. So, we can use it instead.

https://github.com/krausest/js-framework-benchmark/blob/b8cde12fc12cee09ae7652b7bc4a481877582776/broken-frameworks/keyed/react-tracked/src/main.jsx#L1-L3

```diff
- import React, { useReducer } from "react";
+ import React, { useReducer, memo } from "react";
  import { createRoot } from 'react-dom/client';
- import { createContainer, memo } from "react-tracked";
+ import { createContainer } from "react-tracked";
```

Let me know if that doesn't work. I need to deep dive then.

**Comment by krausest** [comment]
Thanks - that worked.
