### ISSUE TITLE
use median instead of mean?

### ISSUE THREAD

**Issue by leeoniya** [krausest/js-framework-benchmark#191]
what would the results look like if you took the median value of 5 runs rather than the mean of 10 or 20 runs? the goal being to reduce total test runtime, a mission not unlike #100 (ahem...).

**Comment by krausest** [comment]
I promise to think about it, but I wanted something different first. The [new](https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts-results/table.html) result table allows to compare frameworks using a t-test. 
Turns out that e.g. vanilla-js is not statistically significant faster than domvm for create rows (even at a significance level of 10%). 
Is that useful?

**Comment by leeoniya** [comment]
i'm not certain a sample size of 10 or even 20 is enough to show that a 7% difference is significant.

anecdotally, i have never seen a reported mean where domvm beats vanilla at create rows, so saying that statistically they show no difference tells me the sample size may be too small when the difference is small. i still think a median (or an avg of the middle 2-4 samples) from a set of 10-15 samples will work best.

**Comment by krausest** [comment]
The very [latest](https://rawgit.com/krausest/js-framework-benchmark/23c253a9e2014472978398fd23a485265842f5b6/webdriver-ts-results/table.html) result table allows to play with sample size and median vs. mean.
I took the time to run 25 samples for each framework (exception: react fiber with 20)
You can simulate the number of samples with the slider, only the first n from the 25 will be taken. With the checkbox you can toggle between median and mean.
If you sort by geom. average you'll notice that switching between both has almost no impact for larger sample count. For 5 and less samples it seems like median indeed softens worse results a bit.

The compare view is IMO pretty interesting to get another view on whether it can be said that vue or angular is faster than react:
<img width="382" alt="bildschirmfoto 2017-06-22 um 23 16 53" src="https://user-images.githubusercontent.com/3374055/27456326-f4c291da-57a0-11e7-8b73-28292af5cdf7.png">


I think I'll stick with the mean and 20 samples. Otherwise I already hear people complaining about the lack of statistical care.

**Comment by leeoniya** [comment]
the whole point of using a median is so you're not forced to run 25 painful iterations and still be fairly confident that your result wasnt majorly skewed by 1 or 2 outliers.

i'm fine with leaving the table to use means as long as you're okay running 25 iterations, but please leave the median collection and toggle option there for authors who are interested in iterating quickly during testing their optimizations.

**Comment by krausest** [comment]
Nah - 25 is too painful - isn't finished next moring, but I'm fine with 20.
You can already use the --count argument for the selenium test driver to adjust the sample size. I'd prefer to add a command line flag to npm results to toggle between median and mean.
