### ISSUE TITLE
"startup" measurement woes

### ISSUE THREAD

**Issue by leeoniya** [krausest/js-framework-benchmark#211]
hey @krausest 

tried running the benchmarks on a recent dev version of chromium and it mostly worked, besides `startup time`, which gets a huge negative number. dunno if this is a simple tweak or a fundamental webdriver/selenium api mismatch/incompatibility.

also, are there any config params for pointing to the chrome binary which is used to run the benches? that would be nice so you can run the bench against portable/temp installs rather than always the system-wide one.

Version 61.0.3152.0 (Official Build) (64-bit)

**Comment by krausest** [comment]
Currently you'd need to hardcode the path like [here](https://github.com/krausest/js-framework-benchmark/blob/master/webdriver-ts/src/benchmarkRunner.ts#L66-L68) and recompile

**Comment by adamhaile** [comment]
FWIW, I get big negative startup time numbers roughly 1/3rd of the time.  This is running current release Chrome (59.0.3071.115) on a new MBP15 (i7 2.9ghz Mac OS 10.12.5).

**Comment by leeoniya** [comment]
yeah, i got that too. i think the table ends up screwed because it averages all those crazy negative values  with the rest rather than ignoring them.

the startup bench is very highly variable and IMO not a great metric. in chrome 61, i get very different startup times across the board for everything, too :/

**Comment by krausest** [comment]
Hmmm - negative numbers sound no good. The startup benchmark tries to compute duration from navigation start to the timestamp of the last paint event. Sounds not too bad, does it?

An alternative approach is currently commented out in https://github.com/krausest/js-framework-benchmark/blob/master/webdriver-ts/src/benchmarkRunner.ts#L224-L225
If you uncomment it, does it create more reasonable results?

I tried Version 61.0.3161.0 (Offizieller Build) canary (64-Bit) and got the following results for the startup benchmark with count 3:
...
result domvm-v3.0.1-non-keyed_30_startup.json 41.806 48.016 43.92166666666666 2.895671060201571
result domvm-v3.0.1-keyed_30_startup.json 44.542 47.635 45.57666666666666 1.4554683858546087
...
result surplus-v0.4.0-keyed_30_startup.json 35.94 40.853 38.839 2.1010808329682775
result surplus-v0.4.0-non-keyed_30_startup.json 40.978 42.067 41.42566666666667 0.46519553833725513
...
The reported numbers are min, max, avg and std dev. All of them look reasonable to me and I didn't observe negative numbers. Even variation seems quite ok.

Any idea how I might reproduce your observation?

**Comment by krausest** [comment]
I guess you certainly did - so please excuse the silly question - but the browser window was visible all the time during the benchmark?
Seems like chrome does not report paint events otherwise reliably.

**Comment by adamhaile** [comment]
@krausest heh, not a silly question at all :) On my last two laptops, when I ran the benchmark the browser always popped up on top of the other apps.  On my new one, it pops up behind them.  I figured maybe something changed with Mac OS' behavior?  Dunno.  So that could definitely be related. I'll try a few runs where I manually swap it to the foreground and see I get any negative startups.

**Comment by adamhaile** [comment]
Re-arranged windows so that the browser was always visible.  Still got a negative number on 1 of 4 runs :(.

**Comment by krausest** [comment]
@adamhaile The startup benchmark computes now window.performance.timing.loadEventEnd - window.performance.timing.navigationStart
Does that work better for you?
I kept the old measurement and print it on the console and add a warning if the difference between both are very high.
From what I see RAF-based frameworks (e.g. vidom) are now faster which sounds plausible.
The only framework that changes a lot is bobril. So far I've no idea why.

**Comment by krausest** [comment]
I added a sleep to the startup benchmark, maybe you can check if there are 
`*********** chromeDuration is negative` console warnings.
If that helps I'd rather switch back to the old measurement.

**Comment by adamhaile** [comment]
@krausest I ran 10 tests and saw no negative results!

Details, in case they're important: by a run I mean `npm run selenium -- --framework surplus-v0.4.0-keyed --benchmark startup`.

The numbers with the new test seem a little lower than before.  I usually had numbers around 40ms before, these averaged 33ms.  I mention it only in case it's a surprise to you.

Variance seemed tighter.  STDEV was +/- 0.81, or 2.4%.  That's between entire runs, i.e. the results reported in the tables.  That seems a lot better than before, though I never went so far as to quantify it before, just noticed it observationally.

The extra time to run the test, from the sleep, is definitely a bummer, but it beats having to re-run it due to negatives or outliers.

I don't recall any console messages about "chromeDuration is negative" but I did see several about "Large difference between navigation and chrome log."

**Comment by leeoniya** [comment]
yeah, the negatives appear to be gone. but the following accompanies each run:

```
startup duration chrome log:  80.259
*********** Large difference between navigation and chrome log 34 80.259
startup duration navigation timing 34
```

also, i have dev version of domvm that shows up as 2x slower while doing nothing different during load and being fully even with all other metrics. it may add ~100 bytes to the filesize, but nothing to justify the 50% slowdown.

```
vanilla: 35.50ms
domvm 3.0.1: 41.60ms
domvm 3.x-dev: 68.85ms
```

i dunno, the results seem to be more consistent on Macs than Windows machines :/

tested in Chromium 61.0.3152.0 (Official Build) (64-bit), Win10x64

**Comment by leeoniya** [comment]
i re-ran the updated bench on my laptop. indeed, `loadEventEnd - navigationStart` gives much tighter, more consistent and believable results.

**Comment by alexteves** [comment]
I am also plagued by negative values. 
In one instance this caused the 'geometric mean' to be null which then caused errors on `npm run results`. 
Re-running that particular framework corrected the issue.

**Comment by krausest** [comment]
Close due to #330
