### ISSUE TITLE
Not compatible with chromedriver 2.29

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#232]
Chromedriver >= 2.29 has an issue when accessing the performance log more than once. Just the first invocation will return the log entries, all other invocations return no log entries.
See:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1811&q=&colspec=ID%20Status%20Pri%20Owner%20Summary&start=100

I'll wait a bit to see whether the bug gets fixed. The workaround would be to add a event that can be identified in the performance log and access it only once. Not nice thus waiting seems to be the better option.

**Comment by adamhaile** [comment]
I'm getting null results with chromedriver 2.28.  Here's a log: 
[log.txt](https://github.com/krausest/js-framework-benchmark/files/1395829/log.txt)

Platform details:
2017 MBP15, macOS 10.12.6
Chrome 62.0.3202.62 (current release version) 
locale en-us

Trying to resolve, I pulled latest, blew away ./node_modules and ./webdriver-ts/node_modules, ran npm install in both and npm run build-prod in webdriver-ts.  Still getting null results.

The weird thing is that it was working ... then it wasn't.  I *think* that Chrome updated between those two but am not fully sure.  So maybe it's an issue with Chrome 62?

I'm not at all knowledgable about chromedriver (aka thanks for wiring up this project!) but am happy to help with any testing or exploration to fix the issue.

**Comment by krausest** [comment]
I just updated to chrome 62 and see the same. Luckily I was already preparing a fix for this issue that completely changes the performance log handling and actually I just wanted to check whether some differences were just random or my mistake. I'll push an updated later this evening. 
Please keep your eyes open whether the results look plausible.

**Comment by adamhaile** [comment]
I can confirm that the fix resolved the null results issue.  👍 

I'm seeing curious results in the "partial update" benchmark though.

<img width="403" alt="screen shot 2017-10-18 at 9 32 25 pm" src="https://user-images.githubusercontent.com/1620206/31750114-efe59704-b44b-11e7-8ad3-71c20bb5cd59.png">

I see a lot of variability repeating the partial update -- surplus bounces b/w about 19 and 24ms on my laptop -- but that general pattern holds: petit much faster than vanilla, surplus in between.

The performance timeline doesn't back up petit being much faster.

Here's vanillajs:
<img width="272" alt="screen shot 2017-10-18 at 9 38 39 pm" src="https://user-images.githubusercontent.com/1620206/31750243-c1a164ee-b44c-11e7-8de4-35b390ec3d62.png">

surplus:
<img width="278" alt="screen shot 2017-10-18 at 9 39 14 pm" src="https://user-images.githubusercontent.com/1620206/31750254-d226fd6a-b44c-11e7-9581-5dff6a4e210c.png">

petit:
<img width="268" alt="screen shot 2017-10-18 at 9 39 39 pm" src="https://user-images.githubusercontent.com/1620206/31750259-e0055b48-b44c-11e7-9388-4cfee1ea0068.png">

All three spend about the same time in render and paint, but surplus and vanilla are faster in script, meaning they should have been faster overall, not slower.

Any thoughts?

**Comment by krausest** [comment]
I've rerun the benchmark last night (10 iterations) and my results look like that:
<img width="411" alt="bildschirmfoto 2017-10-19 um 07 44 12" src="https://user-images.githubusercontent.com/3374055/31755938-6ff0f9fc-b4a1-11e7-82c4-6bb79e8597fc.png">
Before that I also notices quite high duration for partial update for vanilla-js. When I turned debug logging on, I could see that there were a few major gcs for the slow runs. I also checked chrome's timeline, didn't notice any GC issues here. The run from last night looks much better.

What do you think: Should initBenchmark always force a major gc before running? On the one hand it should/might reduce variance on the other hand GC affects performance and thus should be included.

**Comment by leeoniya** [comment]
imo, i would not force GC until/unless something like #231 lands that measures GC specifically.

i'm also seeing some weird stuff in the new runs. any new outliers make me suspicious.

`replace all rows` for gruu-v1.6.12-keyed was unusually low. i did some investigation and my suspicions were confirmed - it doesnt actually replace all rows in the dom. the same applies to its `swap rows` metric and likely many others - it behaves as if it were non-keyed.

bobril's startup bench is also lower than vanillia in your table, which is new and unusual but i could not test it since the startup timing appears to be broken on Windows:

```
DevTools listening on ws://127.0.0.1:12509/devtools/browser/7b98c1d3-1e54-40f1-ae35-ed43d5f46e5d
after initialized  30_startup 2 gruu-v1.6.12-keyed
after run  30_startup 2 gruu-v1.6.12-keyed
at least one paint event is expected after the navigationStart event [ { type: 'navigationStart',
    ts: 42876240445,
    dur: 0,
    end: 42876240445 },
  { type: 'finishedBenchmark',
    ts: 42876360921,
    dur: 0,
    end: 42876360921 } ]
Benchmark failed at least one paint event is expected after the navigationStart event
Writing screenshot error-gruu-v1.6.12-keyed-30_startup.png
ERROR: at least one paint event is expected after the navigationStart event
QUIT
```

**Comment by adamhaile** [comment]
No conclusions here, but some more exploration ....

It's troubling that on your box, ivi is the fast one, but on mine it's petit.  Petit seems to repeat every time for me.  That makes me think that it's not the frameworks that are being measured, but some kind of artifact of the measurement system, which triggers for different loads on our two machines.

Looking at the durations for individual runs, it seems to be very bimodal.  I see clusters around 12-14ms and 25-27ms.  It seems like petit puts more in the low bin, hence the lower average.  Those aren't quite a frame apart, but close enough to be suggestive.

Looking at a few petit runs, in the timeline, I see some that look like this:

<img width="448" alt="screen shot 2017-10-19 at 5 38 10 pm" src="https://user-images.githubusercontent.com/1620206/31797504-97091f78-b4fc-11e7-963e-6a5baa4591b2.png">

And some that look like this:

<img width="386" alt="screen shot 2017-10-19 at 5 31 30 pm" src="https://user-images.githubusercontent.com/1620206/31797513-a568eaa8-b4fc-11e7-81f5-a93a34df2d0e.png">

The difference is in that last, GPU task: it seems to vary between a couple ms and about a dozen.

Could it be GPU frequency scaling?  Maybe to save power the system only runs the GPU as fast as it thinks it needs to to hit the next frame.  So if it doesn't think it can hit a frame, it goes slow and hits the frame after that.  And (lots of conjecture here, I realize) maybe the click events are more likely to fall into sync with the framerate for some workloads and not others?

I get a lot more reliable and believable results if I use 10k rows instead of 1k:

<img width="400" alt="screen shot 2017-10-19 at 6 49 10 pm" src="https://user-images.githubusercontent.com/1620206/31797792-3e475510-b4fe-11e7-9178-654fa78c5fb3.png">

It's a lot slower test, though.

**Comment by leeoniya** [comment]
maybe 1,000 rows is right around the heuristic threshold. do you get less variance with 500 or 300 rows too?

**Comment by adamhaile** [comment]
@leeoniya I tried using 2k rows, a "run" plus an "add".  300 or 500 would take modifying all the apps to only make that many for a "run".  With 2k rows, variance was smaller but still not great:

<img width="403" alt="screen shot 2017-10-19 at 10 03 13 pm" src="https://user-images.githubusercontent.com/1620206/31801945-5eb62f22-b519-11e7-8247-d15acaab9d42.png">

Also, those numbers aren't stable.  I tried a few runs, and each framework basically got a random number between 19 and 24 each time.  Sometimes petit was fast, sometimes surplus, etc.

¯\\\_(ツ)_/¯

**Comment by leeoniya** [comment]
here's what i get (html table and results folder attached too). the image is using median but mean was very close to median in all cases. [results-table.zip](https://github.com/krausest/js-framework-benchmark/files/1401157/results-table.zip)

@krausest btw, 1000ms was too painful and really unnecessary for me to get stable numbers on my machine. I ran the full bench without a delay as previously and recompiled with a 250ms delay for the 30_startup bench, which was enough to avoid the paint event issue.

System:
```
Windows 10 x64 (Thinkpad T440S)
Core i5-4300U (Intel HD 4400)
Chrome 62.0.3202.62 (64-bit)
```

![results](https://user-images.githubusercontent.com/43234/31811121-fcde5394-b543-11e7-9a83-f07aee5fa790.png)

**Comment by krausest** [comment]
As for partial update I'm still unhappy with the std dev.  I see e.g. for vanillajs cases where a click event is followed by a Layout event (which is the first of all events that benchpress considers to be paint events) that comes 23 msecs later. I fail to observe the same long duration in the chrome timeline for any case that I clicked so far.
Nevertheless increasing the sampling size helps to eliminate those outliers and get the median and mean closer to the results from the timeline.

Currently I really consider performing the partial update on a 10k table. The results for a 1k table are so close that a real comparison is hardly possible (the almost only real answer this benchmark delivers is whether the update is actually partial).  Here's the t-test result for react 16. There are almost no significant results, except:
<img width="921" alt="bildschirmfoto 2017-10-21 um 20 59 11" src="https://user-images.githubusercontent.com/3374055/31855031-c1d0aa62-b6a2-11e7-8afe-00a012c1e1f5.png">
When performing on a 10k table, results are much more interesting:
<img width="1797" alt="bildschirmfoto 2017-10-21 um 20 56 43" src="https://user-images.githubusercontent.com/3374055/31855037-d8b3ee1a-b6a2-11e7-9569-b2f511752371.png">
Of course it's not an every day scenario, but it helps getting significant results.
Any objections to increasing the table size to 10k for partial update?

**Comment by adamhaile** [comment]
👍 from me.  Only downside is that it makes it the longest running test, what with the time to create 10k rows plus 5 warmups.

It's frustrating that we don't seem to be able to get as useful results from chromedriver as we can from the timeline.  Anybody know a chromedriver dev we could ask?

**Comment by krausest** [comment]
@leeoniya Since the sleep feels pretty wrong I added an optional afterBenchmark method, which performs some action after runBenchmark for the startup benchmark. Does the startup benchmark work now? The additional memory benchmarks are now included. Will update the result table the next few days.

@adamhaile partial update is now for a 10k table. 
I checked the events I use against the ones angular benchpress uses. I've logged a result  for vanillajs-keyed:
event 'click', ts: 311645421410
{"method":"Tracing.dataCollected","params":{"args":{"beginData":{"dirtyObjects":407,"frame":"0x254333141df8","partialLayout":false,"totalObjects":12071}},"cat":"devtools.timeline","name":"Layout","ph":"B","pid":51934,"tid":775,"ts":311645444061,"tts":544095}}
This means that in this case the first of all events that benchpress considers to be render events happens 23 msecs after the click (whole duration was 28.6 msecs when considering the other events too). So currently I don't think extracting the results is the problem, but that chrome via chromedriver is sometimes much slower.

**Comment by leeoniya** [comment]
@krausest i'll re-bench soon and let you know.

> partial update is now for a 10k table.

let me play devil's advocate here and say that the more expensive the dom, the more it conceals the lib overhead differences since the additional js time required is typically smaller than the extra render/repaint cost. i actually think all 10k benches are somewhat flawed this way, besides being unrealistic scenarios with 80k live dom nodes; even heavy apps (let's say, gmail inbox) stay under 10k, and the majority land under 5k.

i think getting consistent results as a result of pegging the render/repaint is not a great solution. i would much rather see more runs.

here's the difference i get from summing 8 sequential updates of vanilla keyed

`script/(script+render+paint)`:

- 1k: 2.48% scripting
- 10k: 1.82% scripting

![8-updates-10k](https://user-images.githubusercontent.com/43234/31940527-1c774a10-b884-11e7-9039-d0749b277758.png)
![8-updates-1k](https://user-images.githubusercontent.com/43234/31940528-1c881cfa-b884-11e7-8a9e-352c12ded4d2.png)

**Comment by krausest** [comment]
@leeoniya I'm afraid you guys have a tendency to compare the results of the frameworks and as for partial update the results yield no significance difference.
Here's the t-test result for 1k rows and count = 20 (!) and comparison against domvm 
<img width="1205" alt="bildschirmfoto 2017-10-24 um 21 31 57" src="https://user-images.githubusercontent.com/3374055/31964016-f90d0770-b902-11e7-945f-de32a8907a7b.png">
Here's the same for count = 10 and 10k rows:
<img width="1322" alt="bildschirmfoto 2017-10-24 um 21 33 54" src="https://user-images.githubusercontent.com/3374055/31964067-1ab46332-b903-11e7-8311-f7934a1d25f4.png">
Clearly allows a better comparison. I didn't check yet, but I'd say the rendering duration for all frameworks should be rather equal as long as they perform a partial update. Thus though the ratio of script to whole duration is lower for 10k rows it might pronounce the differences in scripting duration better.
