### ISSUE TITLE
startup bench acting up again, bails with error

### ISSUE THREAD

**Issue by leeoniya** [krausest/js-framework-benchmark#286]
Win10, 62.0.3202.89 (Official Build) (64-bit)

![startup_bench_fail](https://user-images.githubusercontent.com/43234/32680400-18a9f07c-c630-11e7-83f1-6b15fdc909af.png)

**Comment by krausest** [comment]
Sorry to hear. I really hate to insert wait conditions, because the right amount doesn't exist thus I'd like to investigate further.
In 1ee151282eac39317ec4fa2ab3d4abc880a335d7 I changed the waiting condition and in dc69cd830a652199ed487b8dde9156895e40fa19 the logging. Seems like in your case there's really no paint event logged. The improved logging should show whether the afterBenchmark event is logged or if the log is truncated.

**Comment by leeoniya** [comment]
thanks, i'll post the log in a bit.

**Comment by leeoniya** [comment]
[log.txt](https://github.com/krausest/js-framework-benchmark/files/1475446/log.txt)

**Comment by krausest** [comment]
Wow - that's scary. 

First the workaround:
I added the config option STARTUP_DURATION_FROM_EVENTLOG which now defaults to false. Then the startup benchmark uses only window.performance.timing to measure the duration. Only if the option is set to true I'm still bothering with computing the startup duration from the event log - which might solve your problem.

Then the analysis:
The interesting part of the startup benchmark is

1. Benchmark runner executes console.timeStamp('runBenchmark')
2. Startup Benchmark loads the URL
3. Startup Benchmark waits for #run to be available
4. Benchmark runner execute console.timeStamp('finishedBenchmark')

The result computation requires a least one paint event to happen between 1 and 4. In your log there are indeed none, so the checks work as intended. I've no idea why the selector works, but the repaint hasn't happened yet.

**Comment by leeoniya** [comment]
👍
