### ISSUE TITLE
Maybe adding one row at a time for 1000 times is a better test?

### ISSUE THREAD

**Issue by kun-zhou** [krausest/js-framework-benchmark#328]
Isn't adding one row at a time for 1000 times is a better and more realistic than adding 1000 rows at a time? The motivation is that we as users care more about how long it takes to make one click adding 1 row rather than the time it takes to add 1000 rows all at once, which isn't really something you do in a real app. Adding 1000 rows at once make the overhead of one rendering cycle non-obvious. But that one rendering cycle's time is what we users really care about since most UI interactions are one click by one click. 

Just a thought.

**Comment by krausest** [comment]
So far I refrained from measuring the duration of multiple actions. I think it would be wrong to include the latency of the selenium webdriver, thus I'd have to extract each of the 1000 durations from each click event to its final paint event and add them up. The duration for each will be very short so that might sum a lot of noise.

To be honest: I've not decided yet whether I'll take the time to try that.

**Comment by paulfalgout** [comment]
I think a major cost comparison is how event delegation is handled.  event delegation for 1 item is the same no matter the event delegation strategy, but a poor system of event delegation is much more obvious for a large list.

**Comment by krausest** [comment]
I'm not further investigating this. I've just added CPU throttling for the short running benchmarks.
