### ISSUE TITLE
WebDriverError: cannot parse capability: chromeOptions

### ISSUE THREAD

**Issue by hville** [krausest/js-framework-benchmark#331]
Running the latest in Windows 10:

```
...\webdriver-ts>npm run selenium -- --count 3 --framework vanillajs-keyed

Benchmark failed { WebDriverError: unknown error: cannot parse capability: chromeOptions
from unknown error: unrecognized chrome option: perfLoggingPrefs
(Driver info: chromedriver=2.9.248315,platform=Windows NT 6.3 x86_64)
```

**Comment by krausest** [comment]
The chromedriver version number seems strange. I'd expect chromedriverVersion: '2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2)' or similar. Is there possible an old chromedriver on your path?
(There's even a hidden possibility in the code to select a specific chromedriver.exe. If you uncomment https://github.com/krausest/js-framework-benchmark/blob/07add4abb7fe3c13ef8af62794fcde1b8d28613a/webdriver-ts/src/benchmarkRunner.ts#L259-L260 and remove the following 4 lines you should be able to pass a --chromeDriver argument pointing to the correct chromeDriver. It's currently not the default because I ran into #303)

**Comment by hville** [comment]
Thanks. It was indeed the chromedriver version. Tried removing it from the the path to no avail; looks like a previous Selenium install added lots of registry entries.

I finally solved it by updating the chromedriver on my machine directly
