### ISSUE TITLE
FUD through the wrong table results

### ISSUE THREAD

**Issue by WebReflection** [krausest/js-framework-benchmark#355]
> Never thought HyperHTML had such a low performance

[This comment](http://www.stefankrause.net/wp/?p=454#comment-732) is inevitable. The linked [table in this page](http://www.stefankrause.net/wp/?p=454) is still the **wrong** one, showing hyperHTML within non keyed results.

At some point I've seen an updated table with hyperHTML in the right place, can you please link to that table ASAP instead of keep showing unfair comparison and performance with hyperHTML?

Thank you.

**Comment by krausest** [comment]
Please let me set a few things straight:
* I really try me best to create a benchmark that is as objective as possible
* The PR (that you contributed to) for hyperhtml classified it as non-keyed. I think I din't check whether that classification was correct which is my fault. After updating to 2.1.2 I noticed that the non-keyed version was also keyed (https://github.com/krausest/js-framework-benchmark/pull/309#issuecomment-346124336) and we removed the non-keyed version
* Each round of the framework reflects the results at a certain point of time, which means for hyperhtml that results are for v1.12.5 in round 7. 
* On master hyperhtml is currently at v2.4.0 and quite fast:
<img width="616" alt="bildschirmfoto 2018-02-03 um 20 31 23" src="https://user-images.githubusercontent.com/3374055/35770750-61498282-0921-11e8-93ad-6495c80bde48.png">

* There results are not yet published but the table on [master](https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts-results/table.html) shows that results today.
* Let's take a look at what the table would have looked like if hyperhtml v1.12.5 would have been classified as keyed. It would have been faster, but not fast:
<img width="435" alt="bildschirmfoto 2018-02-03 um 20 36 12" src="https://user-images.githubusercontent.com/3374055/35770771-fced94b2-0921-11e8-873b-2296a40760a6.png">

How to we deal with this?
* I'm not going to update Round 7's result table in a way that includes a newer version of hyperhtml, since it wasn't there at that time and I can't recreate comparable results (alone due to browser + OS versions).
* Since in all likelihood I made the mistake of publishing a wrong classification for hyperhtml I've already added a remark on my blog that it was classified incorrectly and that performance is better for version 2.4.0
* I could remove hyperhtml v1.12.5 results from the round 7 result table. Do you want me to do that?

**Comment by WebReflection** [comment]
look, I really do appreciate all the work you do but try to imagine I'm also trying very hard to promote a new way to develop Web where performance and patterns used are key to differentiate from the rest.

People keep reading benchmarks without context and seeing hyperHTML in the wrong table, hence inferior to other libraries with keyed capabilities, and with an unfair result since it's in the wrong table, hence people do think and write comments like that, destroys the reputation of the library right away.

So please, **remove** hyperHTML from that post. I rather wait for the next round at least with a fair comparison, in the right table.

**Thanks a lot**

**Comment by krausest** [comment]
Has been removed.
