### ISSUE TITLE
Automated test runs have a trend to run longer for each consecutive run

### ISSUE THREAD

**Issue by Alexander-Taran** [krausest/js-framework-benchmark#375]
Running a benchmark for one test produces increasing over time results

For the following benchmark runs, notice the trend for cpu time.
It steadily increases for each run.
Checked on two different boxes

yarn selenium --count 10 --framework react-v16.1.0-keyed  --benchmark 05_

```
{
    "framework": "react-v16.1.0-keyed",
    "benchmark": "05_swap1k",
    "type": "cpu",
    "min": 143.35,
    "max": 165.883,
    "mean": 150.12820000000002,
    "median": 147.577,
    "geometricMean": 149.9899010135873,
    "standardDeviation": 6.5547284276314635,
    "values": [
        143.35,
        144.187,
        145.593,
        146.429,
        147.074,
        148.08,
        150.784,
        153.298,
        156.604,
        165.883
    ]
}
```

yarn selenium --count 10 --framework vue-v2.5.3-keyed  --benchmark 05_ 

```
{
    "framework": "vue-v2.5.3-keyed",
    "benchmark": "05_swap1k",
    "type": "cpu",
    "min": 51.671,
    "max": 75.257,
    "mean": 66.8957,
    "median": 67.283,
    "geometricMean": 66.51271760851245,
    "standardDeviation": 6.908922000572883,
    "values": [
        51.671,
        58.62,
        65.352,
        66.945,
        66.992,
        67.574,
        68.764,
        72.681,
        75.101,
        75.257
    ]
}
```

yarn selenium --count 100 --framework aurelia-v1.1.5-non-keyed  --benchmark 05_ 
```
{
    "framework": "aurelia-v1.1.5-non-keyed",
    "benchmark": "05_swap1k",
    "type": "cpu",
    "min": 11.667,
    "max": 44.557,
    "mean": 20.461249999999996,
    "median": 20.791,
    "geometricMean": 20.10100657907201,
    "standardDeviation": 3.9583844592838626,
    "values": [
        11.667,
        11.716,
        11.723,
        12.501,
        13.068,
        13.268,
        13.992,
        14.8,
        15.779,
        25.318,
        .... some lines skipped
        25.566,
        26.284,
        27.331,
        44.557
    ]
}
```

**Comment by huochunpeng** [comment]
I can repeat it.

```
{
  "framework": "react-v16.1.0-keyed",
  "benchmark": "05_swap1k",
  "type": "cpu",
  "min": 224.231,
  "max": 229.331,
  "mean": 226.59539999999998,
  "median": 226.18,
  "geometricMean": 226.58909148215693,
  "standardDeviation": 1.6916928326383613,
  "values": [
    224.231,
    224.57,
    225.248,
    225.59,
    226.128,
    226.232,
    227.658,
    228.412,
    228.554,
    229.331
  ]
}
```

```
{
  "framework": "vue-v2.5.3-keyed",
  "benchmark": "05_swap1k",
  "type": "cpu",
  "min": 24.888,
  "max": 34.121,
  "mean": 28.523299999999995,
  "median": 27.307000000000002,
  "geometricMean": 28.386478914703087,
  "standardDeviation": 2.843957877676813,
  "values": [
    24.888,
    25.942,
    26.148,
    27.034,
    27.286,
    27.328,
    29.712,
    30.668,
    32.106,
    34.121
  ]
}
```

**Comment by krausest** [comment]
Ok - was as I thought. The results are sorted. There used to be a good reason for it since there was an option to drop the slowest runs, but this option was removed, but not the sorting...

Without sorting the results look rather ok. 

<img width="691" alt="bildschirmfoto 2018-04-07 um 09 54 29" src="https://user-images.githubusercontent.com/3374055/38452708-b3277baa-3a49-11e8-8dcd-3e7ba7ada760.png">

**Comment by Alexander-Taran** [comment]
It's good to hear that. I'll dig a bit more.. I still think that running them repeatedly somehow has side effects .

Bot no progression in timing is good. (-:

**Comment by Alexander-Taran** [comment]
I still observe some strange behavior on long runs with more than 10 iterations for each benchmark.
It might be my machine but chrome stays in the process list with 100% core usage.
So at some point every next run is slow because all cores are busy.

**Comment by huochunpeng** [comment]
You probably can try forcing the runner to use other browsers, the behaviour may be different.

I guess this is might be the "feature" JavaScript inherited from any languages with VM, the gc will freeze the world every once a while. Benchmark sounds like a typical use case of creating lots of objects.

Maybe try this in every run to normalise the effect.
https://stackoverflow.com/questions/13950394/forcing-garbage-collection-in-google-chrome#13951759

**Comment by krausest** [comment]
If you want to experiment here are some pointers - I'm very interested in hearing any findings.

1. For CPU and Memory Benchmarks the chrome instance (chrome driver to be precise) is recycled. The startup benchmark doesn't do that. It should be pretty simple to change that behaviour if you adjust runMemOrCPUBenchmark to recreate and destroy the driver in each iteration like runStartupBenchmark does.
2. Memory benchmarks force a GC after each iteration (see runBenchmark and initBenchmark). One could do that for CPU benchmarks as well.
I decided against 1 and 2 because 1 would cause a longer duration for all tests and 2 might mask frameworks that alloc lots of memory.
If there's really slow down after some allocations I might reconsider that of course.

**Comment by Alexander-Taran** [comment]
I'm more concerned about partial update case.. where most of the time spent is in layouting..
when browser recalculates all the cell widths for 10k rows.
And it mostly depends on weather framework can replace all the content at once.. or one by one.
We've experimented a bit around and were able to drop 160ms timing to 10ms..  for aurelia that is.
