### ISSUE TITLE
Row node re-use and max clone count

### ISSUE THREAD

**Issue by luwes** [krausest/js-framework-benchmark#643]
Just wanted to ask if there are any objections to these ways of doing the rendering. I think Mikado opened the door on the first one, unless I'm misunderstanding the code.

1. The first idea is to not diff any rows at all but loop over the current rows in the table in the DOM and update the dynamic data (not creating new row nodes), if the list gets bigger create new rows and fill it with the data, if it gets smaller discard some rows. This is quite easy to do when you know the "path" to the dynamic parts of the row template. It's more like overwriting than diffing.

2. With the first concept in mind are there any limitations on how many rows one can clone (with `cloneNode`)? I'm not fully sure this would improve performance but what if one keeps 10 or 100 rows in memory and instead of clone 1 by 1, clone 10 or 100 a time to get to the end count of 1000 and 10000. Again with the dynamic path the template holes can filled after.

**Comment by krausest** [comment]
If more frameworks go that way we might need filterable flags whether a framework is data-driven and whether it's reactive to changes...
Mikado is neither. It's as explicit as the vanillajs version. (From a developer's perspective I'd prefer a reactive data driven framework for almost all non trivial applications, but for the rest something like mikado might be nicer than vanillajs.)

**Comment by leeoniya** [comment]
relevant: https://old.reddit.com/r/javascript/comments/d5k5uq/mikado_020_released_webs_smartest_templating/

**Comment by luwes** [comment]
thanks @leeoniya. point 1 is basically unkeyed I guess 😅 *walks away in shame*
cloning multiple rows could still increase performance I think for creation, I'll have a go at it 😃

**Comment by luwes** [comment]
it's around 20-40% faster with a row clone count of 100. 
https://jsperf.com/1-big-clonenode-vs-multiple-small/1

**Comment by ryansolid** [comment]
That isn't too surprising. But you would have to know how many rows you were doing ahead of time. Even with Mikado's direct-ish manipulation I don't believe it is tailored in a way that it is optimized for the known workflow. Like if we passed different indexes for swap it would still work the same. However, knowing that you are doing 10 or 1000 rows at a time seems very specific thing to know before the data is loaded. I suppose in a real application you have paging sizes so you could leverage this and still be generally faster even dropping the extra rows on the last fetch. Now that I'm talking it out it is a bit more interesting area than I gave it credit for initially, but I think it basically compromises a benchmark like this since it leverages the fact that things are simplistic (only ever 1 or 10k). The tradeoffs that come from working through a system like that are interesting and this benchmark would not display that at all. It becomes uninteresting in the same way as the Vanilla implementation is.

**Comment by luwes** [comment]
Great feedback @ryansolid, I'm gonna try a little experiment with it. 

Initially I did imagine to pre-populate the caches on template creation but it does make assumptions of the data length. For example the template could have several row caches 5x, 10x, 50x, 100x and in the reconciler the new creation length would be passed to the template clone function which chooses the right cache for the job.

Like you said on the fly could still have benefits maybe. Was just going through the least amount of steps it would take, it should really have a specific number I think for each row length.

Current:
- 10 rows yield 10 clones and 10 appends = 20 operations.

If we make a 2 row cache for 10 rows:
- 2 clones + 2 appends for cache + 5 clones + 5 appends = 14 operations.

Might be worth it.

**Comment by luwes** [comment]
On the fly caching of rows didn't seem to be faster, pretty sure pre-caches would make the difference but gonna leave it for now.

**Comment by ryansolid** [comment]
Precaches seem reasonable. I was thinking about this again. And I think it is even simpler to do. Realistically the size doesn't actually matter much. Like if you just made it create more than one row whenever it created the template, and then you could pull them out and use them as needed until there was no more. So as long as you were small enough to make up for overshooting the needed amount you'd be fine. In a real app this would be more than fine. You'd just let the dev give a hint on cache size. If they aimed for like 10-25% of page size I think the benefits would generally outweigh the costs.

**Comment by ryansolid** [comment]
Actually the gain you were seeing @luwes was artificial as far as I can tell. Your 2 scenarios aren't equivalent. One creates:
```html
<div><tr>....</tr></div>
<div><tr>....</tr></div>
<div><tr>....</tr></div>
<div><tr>....</tr></div>
```
And the other creates:
```html
<div>
  <tr>....</tr>
  <tr>....</tr>
  <tr>....</tr>
  <tr>....</tr>
</div>
```
Now correcting the first case to be just:
```
<tr>....</tr>
<tr>....</tr>
<tr>....</tr>
<tr>....</tr>
```
Is trivial and comes with almost no additional overhead. However to change the second you need to parse the children nodes. And pretty much any approach here adds back the overhead. Some ways less than others (like document fragments can move their children in a single DOM command), but the gains are negligible over just cloning each 1 at a time and you only get that advantage if you can add them in one go and using all the nodes. It's more like a 10% gain as far as I can tell at 1000 rows and I suspect at smaller sizes and with management, it would be no gain at all. 

Here's a JSPerf showing what I'm talking about. https://jsperf.com/scaling-clonenode/1. All the tests are equivalent except "biggest div" which works like the larger template in your original example (except these are at 1000 instead of 100 rows).

**Comment by luwes** [comment]
🤦‍♂ my bad, those are indeed different structures I was comparing.

makes sense, yea it's probably not worth the added complexity then.

it's fun experimenting, it seems kind of counter intuitive too when we see how much gains the one row clone gives.

here is the on the fly cache experiment I created
https://github.com/luwes/sinuous/commit/7156ede3fbec759f86bf8ab8e144c2b05e6d5407
