### ISSUE TITLE
Question: Check results of frameworks

### ISSUE THREAD

**Issue by fabiosantoscode** [krausest/js-framework-benchmark#682]
Hey there!

(TL;DR: is there a way to test that the frameworks yielded correct results (eg. the tables have the correct data at the end of a single benchmark run)?)

I have a very particular use case for this collection of JS frameworks.

I intend to test my minifier, Terser, to ensure that it's minifying things properly, and @WebReflection has been kind enough to send me a link to this marvelous repository as something that might help me do a functional smoke-test type thing for Terser.

By running a script that minifies every `main` module within the top-level node_modules of every framework benchmark directory you have here, I can already tell whether a new Terser version might crash with some specific code.

IIUC, the `--check` option allows me to run some tests on the frameworks which aren't really functional tests but might tell me something is wrong with Terser if they fail.

What I would like to do, is to insert a test after a benchmark has run, to ensure that the benchmark script has modified the DOM as was expected.

Is this already possible? If not, what kinds of modifications do you think would be required to do so, and would you accept a PR?

Thanks!

**Comment by WebReflection** [comment]
Just trying to help here, the the `webdriver-ts/src/benchmarks.ts` contains the following at its bottom:

```js
export let benchmarks : Array<Benchmark> = [
    benchRun,
    benchReplaceAll,
    benchUpdate,
    benchSelect,
    benchSwapRows,
    benchRemove,
    benchRunBig,
    benchAppendToManyRows,
    benchClear,
    benchReadyMemory,
    benchRunMemory,
    benchUpdate5Memory,
    benchReplace5Memory,
    benchCreateClear5Memory,
    benchStartup,
];
```
However, it would be insane to wait for every framework to complete that, so that such list should be reduced to the following one, ensuring whatever framework is running the test, is capable of passing it:

```js
export let benchmarks : Array<Benchmark> = [
    benchRun,
    benchReplaceAll,
    benchUpdate,
    benchSelect,
    benchSwapRows,
    benchRemove,
    benchClear,
];
```

Once you have that fixed, all you want to do is drop the warmup/repeats from the benchmark, as these have no value to understand if the code works.

To do so, you should change some value within the `webdriver-ts/src/common.ts` file, most important:

```js
{
  REPEAT_RUN: 1,
  REPEAT_RUN_STARTUP: 0,
  TIMEOUT: 2 * 1000,
  WARMUP_COUNT: 0,
}
```

As you can setup `EXIT_ON_ERROR` from command line, you should be able to quickly exit on any test and fail the regression test.

To make it works, you need to `npm run build-prod` within the `webdriver-ts`, and that should be basically it, unless you want to create the result table (for whatever reason), so that you need to `npm run build-prod` within the `webdriver-ts-results` folder too.

### Pick your frameworks

The way I'd personally do it, would be forking this repository and drop from both `frameworks/keyed` and `frameworks/non-keyed` all frameworks that uses similar patterns, as in _hooks_, _vanilla_, _custom elements_, template literals based, or others, keeping the amount of frameworks to test to the minimum, so that it should never take more than few minutes to run the regression test.

Once you've done that, and you've run `npm run build-prod` from the root of the repository, the `npm run bench-all` should either fail or pass as fast as it can.

These are just basic hints, and I don't even know if these would resolve your issue, but that's likely how I'd do regression tests, the question now is how you pass the latest, not released yet, version of _terser_ to their bundlers, but I believe overwriting every benchmark `node_modules/terser` should do, although if I remember correctly, `npm run build-prod` might try to install again from _npm_, instead of using the already installed package, but I am not fully sure about it.

I hope anything I've said could help reaching your goal somehow, which is a great one, so thanks for putting effort in trying not to break libraries with new terser releases 👍

**Comment by krausest** [comment]
@fabiosantoscode Always glad if this benchmark might help 
@WebReflection is already giving a few really good hints.

For your purpose it should be fine to use the minimal repeat count. You can pass this as an option to webdriver-ts like that `npm run bench -- --count 1`.

You might also consider what benchmarks to run. Do you assume that a defect might cause just a single benchmark to fail? If not you could run just a single (fast) benchmark like create 1,000 rows via `npm run bench -- --benchmark 01_ --count 1`. If you want more benchmarks @WebReflection 's selection is pretty good.

If you want to decrease the timeout you'd have to edit common.ts as described above, but that would make the benchmarks only faster in case of errors - I suppose you'd better optimize successful runs.

The webdriver-ts driver checks for the benchmarks that some dom mutations happen as expected and it should always print a summary if any errors happend. There's an option `--exitOnError true` that should cause the test driver to stop on the first error (but I'm not using that options too often so it isn't well tested).

Would it help it we added an option to run only frameworks that use Terser (There's already some package.json parsing logic in https://github.com/krausest/js-framework-benchmark/blob/master/webdriver-ts/src/common.ts#L136)?

The `--check` option is obsolte and doesn't do anything useful anymore.

Another idea would be to use the check whether an implementation behaves keyed (in webdriver-ts `npm run check`). This also checks whether some expected dom mutations happen and it runs rather quickly.

**Comment by fabiosantoscode** [comment]
Thank you both for your help!

I'm interested in running all the frameworks :) The purpose of this functional test is to gather an enormous sample of javascript and smoke-test it, so the more the merrier!

I'm closing this issue since my question has been answered, thanks again!
