### ISSUE TITLE
How to deal with the problems caused by test environment fluctuations

### ISSUE THREAD

**Issue by wottery** [krausest/js-framework-benchmark#684]
hello，when we used the benchmark library, we found that the test data fluctuated greatly. Would you like to ask how do you handle similar problems?

**Comment by krausest** [comment]
Variance is always a bit tricky, so results might indeed vary by a few milliseconds between runs, but their stability should be okay. Some frameworks are in a very close range regarding performance like mikado and solid and the benchmark can't determine a fixed order for those, but  groups (like the frameworks in the range of 1.06-1.08 and those in the 1.2 range) should stay distinct.

There are some important rules to get stable results:
* Reboot the system
* Try to minimize the background processes (especially no e-mail, browser or IDE open)
* Make sure the system isn't performing search indexing, updating the system when running the benchmark, syncing to the cloud etc. (which is why I often have a CPU monitor open. Between the benchmarks the CPU should be idle)

What are the results and the variance you observe?

**Comment by noelmace** [comment]
(@krausest FYI)
I created a new "framework" as a simple copy of "keyed/vanillajs" following instructions in README. But after running benchmarks on both the copy and the original project, there were really big differences between the two.

But following the rules in your comment and making sure Chrome always stay visible (as I use multiple desktops & screens with specific rules), everything's fine now :+1: (see the attached results file)

Durations are way higher than the ones on the website, but I suppose this is only because I'm using a very old computer. Did you already set up something to run everything (Chrome included) in the cloud and make a great CI/CD for that? I tried to use the existing circleci config but it would need some more work (see [this commit](https://github.com/fullwebdev/js-framework-benchmark/commit/e7cf84f591457d7e86f7fb565335b8a647df0b33) (java is still missing)).

**Comment by krausest** [comment]
There once was a working circle ci configuration but I noticed that its usefulness was limited and thus I didn't bother too much when it broke. 
There were too many unreleated build failures (sporadic network issues and timeouts) and thus it didn't help me much finding broken builds.
There is a a Dockerfile in the repo (and some documentation in the wiki) that I use to build and serve all frameworks on my machine. This could be useful for a CI/CD build. I never tried to benchmark on a cloud server since I was afraid that variance could be much worse than on a local machine.

**Comment by krausest** [comment]
I'm closing older issues that won't get fixed.
