### ISSUE TITLE
Don't see anything logged to console

### ISSUE THREAD

**Issue by eyeinsky** [krausest/js-framework-benchmark#711]
I followed the instructions in the readme for keyd vanilla js and don't see anything printed on the console. I'm on linux (nixos), tried both with firefox (74.0) and chromium (80.0.3987.149).

Tried also with preact with same result.

**Comment by ryansolid** [comment]
You are talking about in the browser console right? If you mean in the terminal ignore the rest of my comment.

Maybe we should update the README I think the end of step 3 is no longer true. I forget what issue it was, but a few months ago we started removing the console.log as many implementations had done so to remove any (albeit small) impact they had on performance. Especially in the front where things are very competitive things were so close . If you are running locally consider running the tests from the command line through the webdriver. Basically follow step 4 (instead of just step 3).

**Comment by leeoniya** [comment]
> but a few months ago we started removing the console.log as many implementations had done so to remove any (albeit small) impact they had on performance.

the main reason is cause it both complicates the impls and gives misleading numbers, especially for async or rAF ops.

**Comment by krausest** [comment]
@eyeinsky Sorry. I recently removed the console logging for all frameworks but forgot to update the README. It's fixed now.
