### ISSUE TITLE
Put a link of the result in repository description

### ISSUE THREAD

**Issue by aminya** [krausest/js-framework-benchmark#717]
https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts-results/table.html

**Comment by dickienaut** [comment]
https://krausest.github.io/js-framework-benchmark/current.html

**Comment by ryansolid** [comment]
Also clicking on anything in around the table is a link too (that whole image).. Although maybe not obvious. Technically it isn't what is reflective in repo but what has been updated on the github.io site but it is kept up to date as things are updated in batches.

**Comment by benmccann** [comment]
I just saw where it says:

> The results of this benchmark is outlined on my blog (round 1, round 2, round 3, round 4, round 5, round 6, round 7 and round 8).

I only found https://krausest.github.io/js-framework-benchmark/current.html because of this ticket. But that still says it's not the official result. The last official result is only from 2018, which is really old.

**Comment by ryansolid** [comment]
I wouldn't be surprised if #683 had to do with that. Chrome's performance has been degrading since summer 2019 and there was probably hope that it would pass. It's caused some increased variance in the tests at times and weird performance in specific tests at others. In the past chrome would go through these sort of cycles of 3-4 releases where some versions would vary but generally get back to a relatively good place. This has been pretty much a downward trajectory for a year now. It's hard to pinpoint the new norm.

Chrome 83 is especially compromised. There is an open bug. They think this is fixed by Chrome 85. But I've definitely seen different behavior in 83 that is still present in my canary build, so I'm not sure things are all resolved.

**Comment by leeoniya** [comment]
i guess the argument can be made that numbers for stable versions of chrome should be published "officially" as long as there are no measurement issues.

chrome's layout perf degradation certainly isn't preventing G from pushing it out to hundreds of millions of users. i think it's fair to show the real current perf rather than wait for some anointed "true" leaderboard when perf returns to Chrome 75 levels. 🤷

**Comment by ryansolid** [comment]
@leeoniya you are right. I think only maybe 2 if the versions were particularly bad for measuring.

**Comment by krausest** [comment]
I think I just was sloppy. Actually the results published in #683 could have been official runs.
I mainly added the disclaimer since the result table on the master branch is incrementally updated when merging a pull request (i.e. only the updated implementation is benchmarked). At this point chrome or the OS might have received an update and thus results might not be really comparable.
In recent times I always run all implementations when chrome got a new major version.
I promise to publish official results for chrome 84.

**Comment by krausest** [comment]
I tried to act according to what I said and created a new page for [official results](https://krausest.github.io/js-framework-benchmark/index.html) and adjusted the README such that the page is linked and added a new section for official results in the README.
